config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  # アカウント登録用ページ(for 実験参加者)
  get  '/register', to: 'participants#new'
  post '/register', to: 'participants#create'

  # 被験者マイページ
  get   '/mypage',      to: 'participants#show'

  # 被験者設定ページ
  get   '/settings',  to: 'participants#edit'
  patch '/settings',  to: 'participants#update'
  put   '/settings',  to: 'participants#update'

  # 被験者アカウント削除ページ
  delete '/deactivate', to: 'participants#destroy'

  # 認証ページ(for 実験参加者)
  get    '/login',  to: 'sessions#new_participant'
  post   '/login',  to: 'sessions#create_participant'
  delete '/logout', to: 'sessions#destroy_participant'
  get    '/participant/login', to: redirect('/login')

  # 実験応募ページ
  resources :applications

  # カレンダー確認ページ
  get   '/calendar', to: 'calendar#index'

  # アカウント登録用ページ(for 実験者)
  get  '/member/register', to: 'members#new'
  post '/member/register', to: 'members#create'

  # アカウント有効化ページ(for 被験者)
  get '/activate', to: 'participant_activations#edit'

  # メール更新ページ(for 被験者)
  get '/email_update', to: 'participants_email_update#update'

  # 問い合わせフォーム(for 被験者)
  get  '/inquiries',     to: 'inquiries#index'
  post '/inquiries/new', to: 'inquiries#create'
  get  '/inquiries/new', to: 'inquiries#new'
  #get  '/inquire/:id', to: 'inquiries#show', as: 'inquiry'

  # パスワードリセットフォーム(for 被験者)
  get    '/reset',     to: 'participant_password_resets#new'
  post   '/reset',     to: 'participant_password_resets#create'
  get    '/reset/:id', to: 'participant_password_resets#edit',   as: 'edit_reset'
  patch  '/reset/:id', to: 'participant_password_resets#update', as: 'update_reset'

  # 実験者マイページ
  get   '/member/mypage',      to: 'members#show'
  #get   '/member/mypage/edit', to: 'members#edit'
  #patch '/member/mypage/edit', to: 'members#update'
  #put   '/member/mypage/edit', to: 'members#update'

  # 認証ページ(for 実験者)
  get    '/member/login',  to: 'sessions#new_member'
  post   '/member/login',  to: 'sessions#create_member'
  delete '/member/logout', to: 'sessions#destroy_member'

  # 実験募集ページ
  resources :experiments do
    collection do
      get 'place_checkbox'
    end
  end

  #実験部屋追加ページ
  resources :rooms

  #実験場所追加ページ
  resources :places

  # アカウント有効化ページ(for 実験者)
  get '/member/activate', to: 'member_activations#edit'

  # パスワードリセットフォーム(for 実験者)
  get    '/member/reset',     to: 'member_password_resets#new'
  post   '/member/reset',     to: 'member_password_resets#create'
  get    '/member/reset/:id', to: 'member_password_resets#edit',   as: 'member_edit_reset'
  patch  '/member/reset/:id', to: 'member_password_resets#update', as: 'member_update_reset'

  # admin付与ページ
  get    '/member/approve',     to: 'approve_members#show'
  patch  '/member/approve/:id', to: 'approve_members#update', as: 'update_member_admin'
end

app/models/participant.rb
class Participant < ApplicationRecord
  include Account

  belongs_to :faculty
  has_many :applications, dependent: :destroy
  has_many :inquiries, dependent: :destroy
  has_many :schedules, through: :applications
  has_many :experiments, through: :schedules
  has_many :events, dependent: :destroy

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  VALID_YOMI_REGEX = /[ぁ-んー－\s]+/
  has_secure_password

  before_save { email.downcase! }

  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }
  validates :new_email, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, allow_nil: true
  validate  :validate_email_uniqueness
  validate  :validate_new_email_uniqueness
  validates :password, presence: true, length: { minimum: 8, maximum: 32 }, allow_nil: true

  validates :name, presence: true, length: { maximum: 50 }
  validates :yomi, presence: true, length: { maximum: 50 }, format: { with: VALID_YOMI_REGEX }
  validates :gender, inclusion: { in: 1..2 }
  validates :classification, inclusion: { in: 1..3 }
  validates :grade, inclusion: { in: 1..4 }, if: Proc.new { |a| a.classification == 1 }
  validates :grade, inclusion: { in: 1..2 }, if: Proc.new { |a| a.classification == 2 }
  validates :grade, inclusion: { in: 1..3 }, if: Proc.new { |a| a.classification == 3 }
  validates :address, presence: true, length: { maximum: 255 }
  validates :agreement, acceptance: true
  validate  :validate_birth

  # 生年月日のバリデーション
  def validate_birth
    if birth.nil?
      errors.add(:birth, "を入力してください")
      return
    end

    birth_bc = birth_before_type_cast
    if birth_bc.kind_of?(Hash) # フォームで入力すると元の型がHashなのでそれを拾ってバリデーション
      y = birth_bc[1].to_i
      m = birth_bc[2].to_i
      d = birth_bc[3].to_i
      unless Date.valid_date?(y,m,d)
        errors.add(:birth, "は存在する年月日である必要があります")
      end
    end

    boundary = Date.today.years_ago(18)
    errors.add(:birth, "は#{boundary.to_s}以前である必要があります") if birth > boundary
  end

  # アクティブ被験者のメールアドレスのユニーク性バリデーション
  def validate_email_uniqueness
    # 現在登録されているメールアドレスとのユニーク性
    participant = Participant.find_active_by_email(email.downcase)
    if participant && (id.nil? || participant.id != id)
      errors.add(:email, "は既に登録済みです")
    end

    # 更新予定のメールアドレスとのユニーク性
    participant = Participant.find_active_by_new_email(email.downcase)
    if participant && (id.nil? || participant.id != id) && !participant.email_update_token_expired?
      errors.add(:email, "は既に登録済みです")
    end
  end

  # メール更新時のメールアドレスのユニーク性を検証する
  def validate_new_email_uniqueness
    return true if new_email.nil?
    # 現在登録されているメールアドレスとのユニーク性
    participant = Participant.find_active_by_email(new_email.downcase)
    if participant
      errors.add(:new_email, "は既に登録済みです")
    end

    # 更新予定のメールアドレスとのユニーク性
    participant = Participant.find_active_by_new_email(new_email.downcase)
    if participant && (id.nil? || participant.id != id) && !participant.email_update_token_expired?
      errors.add(:new_email, "は既に登録済みです")
    end
  end

  # 永続セッションのためにトークンをデータベースに記憶する。
  def remember
    self.remember_token = Participant.new_token
    update_attribute(:remember_digest, Participant.digest(remember_token))
  end

  # 永続セッションを破棄するためにトークンをデータベースから破棄する。
  def forget
    update_attribute(:remember_digest, nil)
  end

  # パスワード再設定のメールを送信する
  def send_password_reset_email
    ParticipantMailer.password_reset(self).deliver_now
  end

  # 性別番号を文字列に変換する
  def self.gender_to_s(gender)
    gender == 1 ? '男性' : '女性'
  end

  # メールアドレスから非退会被験者を取得する(既存メソッドのオーバーライド)
  def self.find_by_email(email)
    Participant.find_by(email: email, deactivated: false)
  end

  # new_emailに合わせてオーバーライドではなく新規に関数を定義
  def self.find_active_by_email(email)
    Participant.find_by(email: email, deactivated: false)
  end

  def self.find_active_by_new_email(new_email)
    Participant.find_by(new_email: new_email, deactivated: false)
  end

  def deactivatable?
    for s in schedules do
      if s.datetime > DateTime.now
        for a in s.applications do
          if a.status != ApplicationStatus::CANCELED
            return false
          end
        end
      end
    end
    for e in events do
      if e.start_at > DateTime.now
        return false
      end
    end
    return true
  end
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  before_action :redirect_to_login, only: [:show, :edit, :update, :destroy]
  before_action :redirect_to_mypage, only: [:new, :create]

  def new
    get_options_info
    @participant = Participant.new
  end

  def create
    get_options_info
    @participant = Participant.new(params.require(:participant).permit(
        :name, :yomi, :gender, :classification, :grade, :faculty_id, :address, :birth, :email,
        :password, :password_confirmation, :agreement))
    if @participant.save
      ParticipantMailer.account_activation(@participant).deliver_now
      flash[:info] = "アカウント有効化のためのメールを送信しました。"
      redirect_to login_url
    else
      render 'new'
    end
  end

  def show
    @participant = current_participant
    @applications = Application.where(participant_id: @participant.id, status: [ApplicationStatus::APPLYING, ApplicationStatus::ACCEPTED])
    @events = Event.where(participant_id: @participant.id)
  end

  def edit
    get_options_info
    @participant = current_participant
    @type = 'all'
  end

  def update
    get_options_info
    @participant = current_participant
    @type = params[:type]
    participant_params = nil
    if @type == 'profile'
      participant_params = params.require(:participant).permit(
          :name, :yomi, :gender, :classification, :grade, :faculty_id, :address, :birth)
    elsif @type == 'password'
      participant_params = params.require(:participant).permit(
          :password, :password_confirmation)
    elsif @type == 'email_update'
      participant_params = params.require(:participant).permit(:new_email)
    end
    if @participant.update_attributes(participant_params)
      flash.now[:success] = 'プロフィールを更新しました。' if @type == 'profile'
      flash.now[:success] = 'アカウント情報を更新しました。' if @type == 'password'
      if @type == 'email_update'
        @participant.create_email_update_token_and_digest
        ParticipantMailer.email_update(@participant).deliver_now
        flash.now[:info] = '新しいメールアドレスに確認メールを送信しました。'
      end
    else
      flash.now[:danger] = 'プロフィールの更新に失敗しました。' if @type == 'profile'
      flash.now[:danger] = 'アカウント情報の更新に失敗しました。' if @type == 'password'
      flash.now[:danger] = 'メールアドレスの更新に失敗しました。' if @type == 'email_update'
    end
    render 'edit'
  end

  def destroy
    @participant = current_participant
    if @participant.deactivatable? && @participant.update_attributes(deactivated: true)
      flash[:success] = 'アカウントを削除しました。'
    else
      flash[:danger] = 'アカウントの削除に失敗しました。'
    end
    log_out_participant
    redirect_to login_url
  end

  private

    def get_options_info
      @classifications = {
          "学部生(Bachelor)" => 1,
          "修士課程(Master)" => 2,
          "博士課程(Doctor)" => 3 }
      @faculties = Faculty.where("classification == ?",1).pluck(:name,:id)
      @courses = Faculty.where("classification == ?",2).pluck(:name,:id)
    end

    # ログインしていない場合ログインページへリダイレクトする
    def redirect_to_login
      unless logged_in_participant?
        store_location
        redirect_to login_url
      end
    end

    # ログインしている場合マイページへリダイレクトする
    def redirect_to_mypage
      if logged_in_participant?
        redirect_to mypage_url
      end
    end
end

app/helpers/participants_helper.rb
module ParticipantsHelper
  # 応募の受付状態に対応するカレンダー表示タイトルを返す
  def get_title(status, title)
    case status
      when ApplicationStatus::ACCEPTED
        return title
      else
        return "【申請中】#{title}"
    end
  end
end

app/views/participants/_agreement.html.erb
【利用目的】
入力していただいた個人情報は実験の実施や謝金支払いなどの申請書類を作成する際に利用いたします。

【公開範囲】
前述の書類は京都大学の事務において処理されます。そのため個人情報の公開範囲は研究室及び事務となります。

【保持期間】
実験がすべて終了し、最後にログインしてから一週間が経過するとアカウントが自動的に削除され、データベースに登録された個人情報も破棄されます。
また、研究室での個人情報の保持期間は前述の書類を事務に提出するまでとなります。

app/views/participants/_destroy.html.erb
<p>※実験終了後ログインしないまま7日が経過すると自動的にアカウントが削除されます。</p>

<% if participant.deactivatable? %>
    <%= link_to '今、アカウントを削除する', deactivate_path, method: :delete, title: '確認',
                data: { confirm: '本当にアカウントを削除してよろしいですか？',
                        commit:  '削除する',
                        cancel:  'キャンセル', },
                        class: 'form-control btn btn-danger' %>
<% else%>
    <%= link_to '今、アカウントを削除する',"", disabled: true, class: 'form-control btn btn-danger' %>
    <p> 予定が残っているためアカウントを削除できません。 </p>
<% end %>

app/views/participants/_form.html.erb
<%= form_for(participant, url: form_for_url, html: { class: "form-horizontal" }) do |f| %>
  <%= render 'shared/error_messages', object: f.object if show_errors %>

  <%= hidden_field_tag :type, type %>
  <% if type == 'all' || type == 'profile' %>
    <%= form_text_field f, :name, 'お名前(漢字)', example: '西田 豊明' %>
    <%= form_text_field f, :yomi, 'お名前(ひらがな)', example: 'にしだ とよあき' %>
    <%= form_select f, :gender, '性別', { '男性' => 1, '女性' => 2 }, size: 2 %>
    <%= form_select f, :classification, '学生区分', classifications %>
    <%= form_select f, :grade, '学年', {} %>
    <%= form_select f, :faculty_id, '学部・研究科', {} %>
    <%= form_text_field f, :address, '住所', example: '京都市左京区吉田本町' %>
    <%= form_date f, :birth, '生年月日', 1970, Date.today.year - 17 %>
  <% end %>
  <% if type == 'all' %>
    <%= form_email_field f, :email, 'メールアドレス', description: 'ログインや連絡に用いるため、普段お使いのメールアドレスをご入力ください。' %>
  <% end %>
  <% if type == 'email_update' %>
    <%= form_email_field f, :new_email, 'メールアドレス', description: 'あなたが現在設定しているメールアドレスは"%s"です。' % participant.email %>
  <% end %>
  <% if type == 'all' || type == 'password' %>
    <%= form_password_field f, :password, 'パスワード', description: '半角英数字と記号を組み合わせて、8文字以上の推測されにくいものをご入力ください。' %>
    <%= form_password_field f, :password_confirmation, 'パスワード(確認)' %>
  <% end %>
  <% if type == 'all' %>
    <% agreetext = File.open("#{Rails.root}/app/views/participants/_agreement.html.erb","rb").read.force_encoding("UTF-8") %>
    <%= form_text_area_tag :agreetext, '個人情報の取り扱い', value: agreetext %>
    <div class="form-group">
      <div class="col-sm-2"></div>
      <div class="col-sm-8">
        <div class="checkbox">
          <%= f.label :agreement, class: "checkbox inline" do %>
            <%= f.check_box :agreement,required: true %>
           個人情報の取り扱いに同意する
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
  <%= form_submit f, submit_label %>
<% end %>

<% if type == 'all' || type == 'profile'  %>
  <script type="text/javascript">
    <%= render partial: 'participants/javascripts/form.js',
               locals: { faculties: faculties, courses: courses, participant: participant } %>
  </script>

  <%= javascript_include_tag 'validation' %>
<% end %>

app/views/participants/edit.html.erb
<% provide(:title, '設定') %>
<h2><%= yield(:title) %></h2>

<%= panel(type: 'default',
          header: '<h3>アカウント情報</h3>',
          body: render(partial: 'form',
                       locals: { form_for_url: settings_path, participant: @participant,
                                 classifications: @classifications, faculties: @faculties,
                                 courses: @courses, submit_label: '更新する', type: 'password', show_errors: @type == 'password' })) %>

<%= panel(type: 'default',
          header: '<h3>プロフィール</h3>',
          body: render(partial: 'form',
                       locals: { form_for_url: settings_path, participant: @participant,
                                 classifications: @classifications, faculties: @faculties,
                                 courses: @courses, submit_label: '更新する', type: 'profile', show_errors: @type == 'profile' })) %>

<%= panel(type: 'default',
          header: '<h3>メールアドレス</h3>',
          body: render(partial: 'form',
                       locals: { form_for_url: settings_path, participant: @participant,
                                 classifications: @classifications, faculties: @faculties,
                                 courses: @courses, submit_label: '更新する', type: 'email_update', show_errors: @type == 'email_update' })) %>

<%= panel(type: 'danger',
          header: '<h3>アカウント削除</h3>',
          body: render(partial: 'destroy',
                       locals: { participant: @participant })) %>

app/views/participants/new.html.erb
<% provide(:title, '実験応募フォーム') %>
<h2><%= yield(:title) %></h2>

<p>実験参加にはアカウント登録が必要です。</p>
<p>ログインは<%= link_to 'こちら', login_path %>。</p>

<%= render partial: 'form',
           locals: { form_for_url: register_path, participant: @participant, classifications: @classifications,
                     faculties: @faculties, courses: @courses, submit_label: '仮登録する', type: 'all', show_errors: true } %>

app/views/participants/show.html.erb
<% provide(:title, 'マイページ') %>
<h2><%= yield(:title) %></h2>

<p><%= @participant.name %> さんの予定表です。</p>

<div class="custom-calendar-wrap custom-calendar-full">
  <div class="custom-header clearfix">
    <h3 class="custom-month-year">
      <span id="custom-year" class="custom-year"></span>
      <span id="custom-month" class="custom-month"></span>
      <nav>
        <span id="custom-prev" class="custom-prev"></span>
        <span id="custom-next" class="custom-next"></span>
      </nav>
    </h3>
  </div>
  <div id="calendar" class="fc-calendar-container"></div>
</div>

<script type="text/javascript">
  <%= render partial: 'participants/javascripts/show.js',
             locals: { applications: @applications, events: @events } %>
</script>

<% if Rails.env.test? %>
  <% @applications.each do |a| %>
    <div class='<%= "#{a.schedule.experiment.name}#{a.status}" %>'></div>
  <% end %>
  <% @events.each do |e| %>
      <div class='<%= "#{e.name}#{e.experiment.name}" %>'></div>
  <% end %>
<% end %>