config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  # アカウント登録用ページ(for 実験参加者)
  get  '/register', to: 'participants#new'
  post '/register', to: 'participants#create'

  # 被験者マイページ
  get   '/mypage',      to: 'participants#show'

  # 被験者設定ページ
  get   '/settings',  to: 'participants#edit'
  patch '/settings',  to: 'participants#update'
  put   '/settings',  to: 'participants#update'

  # 被験者アカウント削除ページ
  delete '/deactivate', to: 'participants#destroy'

  # 認証ページ(for 実験参加者)
  get    '/login',  to: 'sessions#new_participant'
  post   '/login',  to: 'sessions#create_participant'
  delete '/logout', to: 'sessions#destroy_participant'
  get    '/participant/login', to: redirect('/login')

  # 実験応募ページ
  resources :applications

  # カレンダー確認ページ
  get   '/calendar', to: 'calendar#index'

  # アカウント登録用ページ(for 実験者)
  get  '/member/register', to: 'members#new'
  post '/member/register', to: 'members#create'

  # アカウント有効化ページ(for 被験者)
  get '/activate', to: 'participant_activations#edit'

  # メール更新ページ(for 被験者)
  get '/email_update', to: 'participants_email_update#update'

  # 問い合わせフォーム(for 被験者)
  get  '/inquiries',     to: 'inquiries#index'
  post '/inquiries/new', to: 'inquiries#create'
  get  '/inquiries/new', to: 'inquiries#new'
  #get  '/inquire/:id', to: 'inquiries#show', as: 'inquiry'

  # パスワードリセットフォーム(for 被験者)
  get    '/reset',     to: 'participant_password_resets#new'
  post   '/reset',     to: 'participant_password_resets#create'
  get    '/reset/:id', to: 'participant_password_resets#edit',   as: 'edit_reset'
  patch  '/reset/:id', to: 'participant_password_resets#update', as: 'update_reset'

  # 実験者マイページ
  get   '/member/mypage',      to: 'members#show'
  #get   '/member/mypage/edit', to: 'members#edit'
  #patch '/member/mypage/edit', to: 'members#update'
  #put   '/member/mypage/edit', to: 'members#update'

  # 認証ページ(for 実験者)
  get    '/member/login',  to: 'sessions#new_member'
  post   '/member/login',  to: 'sessions#create_member'
  delete '/member/logout', to: 'sessions#destroy_member'

  # 実験募集ページ
  resources :experiments do
    collection do
      get 'place_checkbox'
    end
  end

  #実験部屋追加ページ
  resources :rooms

  #実験場所追加ページ
  resources :places

  # アカウント有効化ページ(for 実験者)
  get '/member/activate', to: 'member_activations#edit'

  # パスワードリセットフォーム(for 実験者)
  get    '/member/reset',     to: 'member_password_resets#new'
  post   '/member/reset',     to: 'member_password_resets#create'
  get    '/member/reset/:id', to: 'member_password_resets#edit',   as: 'member_edit_reset'
  patch  '/member/reset/:id', to: 'member_password_resets#update', as: 'member_update_reset'

  # admin付与ページ
  get    '/member/approve',     to: 'approve_members#show'
  patch  '/member/approve/:id', to: 'approve_members#update', as: 'update_member_admin'
end

app/models/experiment.rb
class Experiment < ApplicationRecord
  belongs_to :member
  belongs_to :room
  has_many :schedules, dependent: :destroy
  has_many :applications, dependent: :destroy
  has_many :inquiries, dependent: :destroy
  has_many :participants, through: :applications
  has_many :events, dependent: :destroy
  has_many :ex_places, inverse_of: :experiment
  accepts_nested_attributes_for :ex_places, allow_destroy: true

  validate :validate_schedule

  validates :member_id, presence: true
  validates :member, presence: true
  validates :project_owner, presence: true
  validates :room_id, presence: true
  validates :room, presence: true
  validates :name, uniqueness: true
  validates :budget, presence: true
  validates :department_code, presence: true
  validates :project_num, presence: true
  validates :project_name, presence: true
  validates :creditor_code, presence: true
  validates :expected_participant_count, presence: true
  validates :duration, presence: true
  validates :name, presence: true, length: { maximum: 200 }
  validates :description, presence: true, length: { maximum: 400 }

  private
  # 実験予定がfromからtoまでで正しい期間になっているかをチェック
  def validate_schedule
    nil_check = false
    if schedule_from.nil?
      errors.add(:schedule_from, "実験予定の開始日を入力してください")
      nil_check = true
    end
    if schedule_to.nil?
      errors.add(:schedule_to, "実験予定の終了日を入力してください")
      nil_check = true
    end
    if nil_check
      return
    end

    if schedule_from > schedule_to
      errors.add(:schedule_to, "実験予定の終了日を開始日より後にしてください。")
    end
  end
end

app/controllers/experiments_controller.rb
class ExperimentsController < ApplicationController
  include MembersCommon
  include SchedulesCommon
  before_action :redirect_to_member_login, except: :place_checkbox
  before_action :redirect_to_member_mypage_exclude_admin, except: :place_checkbox

  def index
    redirect_to member_mypage_url
  end

  def new
    @experiment = Experiment.new
  end

  def create
    @member = current_member

    @experiment = Experiment.new(experiment_param_for_create)
    @experiment.member_id = @member.id

    if @experiment.save
      redirect_to member_mypage_url
    else
      render 'new'
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def show
    if params[:id].nil?
      redirect_to experiments_url
    end

    @member = current_member
    @experiment = Experiment.find_by_id(params[:id])

    # 自分の実験じゃない場合はマイページにリダイレクトする
    if @experiment.nil? || @member.id != @experiment.member_id
      redirect_to member_mypage_url
    else
      @times = get_times(Schedule.where(experiment_id: @experiment.id), [ApplicationStatus::APPLYING, ApplicationStatus::ACCEPTED])
    end
  end

  def place_checkbox
    if logged_in_member?
      places = Place.where(room_id: params[:room_id])
      render partial: 'experiments/ex_place_form', locals: {places: places}
    else
      render partial: 'experiments/ex_place_form_error'
    end
  end

  private
    def experiment_param_for_create
      params[:experiment][:ex_places_attributes].each { |index, hash| \
        hash[:_destroy] = hash[:place_id].blank? }
      params.require(:experiment).permit(
        :zisshi_ukagai_date, :project_owner, :room_id, :budget,
        :department_code, :project_num, :project_name, :creditor_code,
        :expected_participant_count, :duration, :name, :description,
        :schedule_from, :schedule_to, :id,
        ex_places_attributes: [
          :place_id,
          :_destroy,
        ],)
    end

end

app/views/experiments/_ex_place_form.html.erb
<% places.each_with_index do |p, index| %>
  <% name_prefix = "experiment[ex_places_attributes][#{index}]" %>
  <%= hidden_field_tag "#{name_prefix}[id]" %>
  <%= form_check_box_tag "#{name_prefix}[place_id]", p[:detail], value: p[:id] %>
<% end %>

app/views/experiments/_ex_place_form_error.html.erb
<div class='form-group'>
  <div class="col-sm-2"></div>
  <div class="col-sm-8">
    ログアウトしています。再度ログインしてからやり直してください。
  </div>
</div>

app/views/experiments/_form.html.erb
<script type="text/javascript" class="create_places_checkbox">
  <%= render partial: "experiments/javascripts/create_places_checkbox.js" %>
</script>

<%= form_for experiment, url: form_for_url, html: { class: "form-horizontal" } do |f| %>
  <%= render 'shared/error_messages', object: f.object if show_errors %>

  <%= hidden_field_tag :type, type %>
  <% if type == 'all' || type == 'profile' %>
    <%= form_date f, :zisshi_ukagai_date, '実施伺日', 1970, Date.today.year - 17 %>
    <%= form_text_field f, :name, '実験名', example: 'ほげのためのふが実験' %>
    <%= form_text_field f, :project_owner, 'プロジェクト責任者', example: '実際はadd可能なプルダウン？' %>
    <%= form_text_field f, :project_num, 'プロジェクト番号' %>
    <%= form_text_field f, :project_name, 'プロジェクト名' %>
    <%= form_text_field f, :budget, '予算科目' %>
    <%= form_text_field f, :creditor_code, '債主コード' %>
    <%= form_text_field f, :department_code, '部署コード' %>
    <%= form_collection_select f, :room_id, '実施場所', Room.all, :id, :name, prompt: "-------------------------------------------------------" %>
    <div id="places_checkbox">
    </div>
    <%= form_text_field f, :expected_participant_count, '予定人数', unit: '人' %>
    <%= form_text_field f, :duration, '時間数(単位はh)', unit: '時間' %>
    <%= form_text_field f, :description, '実験概要' %>
    <%= form_date_fromto f, :schedule_from, :schedule_to, '実施予定日(from~to)', 1970, Date.today.year - 17 %>
  <% end %>
  <%= form_submit f, submit_label %>
<% end %>

app/views/experiments/_roomform.html.erb
<%= form_for(room, url: form_for_url, html: { class: "form-horizontal" }) do |f| %>
  <%= render 'shared/error_messages', object: f.object if show_errors %>

  <%= hidden_field_tag :type, type %>
  <% if type == 'room' %>
    <div class='form-group'>
      <%= label('dummy',"既存の部屋", class: 'col-sm-2 control-label') %>
      <div class='col-sm-8'>
        <% Room.all.each do |r| %>
        <%= r.name %>
        <% end %>
      </div>
    </div>
    <%= form_text_field f, :name, '部屋名' %>
  <% end %>
  <% if type == 'place' %>
  <div class='form-group'>
    <%= label('dummy',"既存の場所", class: 'col-sm-2 control-label') %>
    <div class='col-sm-8'>
      <% Room.all.each do |r| %>
       <b>
        <%= r.name %>
       </b>
        <% Place.where(room_id: r.id).each do |p| %>
          <%= p.detail %>
        <% end %>
        <br>
      <% end %>
    </div>
  </div>
    <%= form_collection_select f, :room_id, '実施場所', Room.all, :id, :name, prompt: "-------------------------------------------------------" %>
    <%= form_text_field f, :detail, '場所名' %>
  <% end %>
  <%= form_submit f, submit_label %>
<% end %>

app/views/experiments/new.html.erb
<% provide(:title, '実験募集フォーム') %>
<h2><%= yield(:title) %></h2>

<%= render partial: 'form',
           locals: { form_for_url: experiments_path, experiment: @experiment, submit_label: '募集する', type: 'all', show_errors: true } %>

app/views/experiments/newroom.html.erb
<% provide(:title, '実験場所追加フォーム') %>
<h2><%= yield(:title) %></h2>
<div class="panel panel-primary">
  <div class="panel-heading"><%= simple_format("部屋追加") %></div>
  <div class="panel-body">
    <%= render partial: 'roomform',
               locals: { form_for_url: experiment_newroom_path, room: @room, submit_label: '追加する', type: 'room', show_errors: true } %>
  </div>
</div>

<div class="panel panel-primary">
  <div class="panel-heading"><%= simple_format("場所追加") %></div>
  <div class="panel-body">
    <%= render partial: 'roomform',
               locals: { form_for_url: experiment_newroom_path, room: @place, submit_label: '追加する', type: 'place', show_errors: true } %>
  </div>
</div>

app/views/experiments/show.html.erb
<% provide(:title, '実験情報ページ') %>
<h2><%= yield(:title) %></h2>
<p>
  <%= "id: #{@experiment.id}, 名前: #{@experiment.name}" %>
</p>
<h3>実験参加者一覧</h3>
<table border="1">
  <tr><th>名前</th><th>よみ</th><th>from</th><th>to</th><th>分類（学部1, 修士2, 博士3）</th><th>AppStatus</th></tr>
  <% @times.each do |t| %>
    <% t[:p_infos].each do |p_info| %>
      <tr>
        <td><%= p_info[:name] %></td>
        <td><%= p_info[:yomi] %></td>
        <td><%= t[:start] %></td>
        <td><%= t[:end] %></td>
        <td><%= p_info[:classification] %></td>
        <td><%= p_info[:status] %></td>
      </tr>
    <% end %>
  <% end %>
</table>