config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  # アカウント登録用ページ(for 実験参加者)
  get  '/register', to: 'participants#new'
  post '/register', to: 'participants#create'

  # 被験者マイページ
  get   '/mypage',      to: 'participants#show'

  # 被験者設定ページ
  get   '/settings',  to: 'participants#edit'
  patch '/settings',  to: 'participants#update'
  put   '/settings',  to: 'participants#update'

  # 被験者アカウント削除ページ
  delete '/deactivate', to: 'participants#destroy'

  # 認証ページ(for 実験参加者)
  get    '/login',  to: 'sessions#new_participant'
  post   '/login',  to: 'sessions#create_participant'
  delete '/logout', to: 'sessions#destroy_participant'
  get    '/participant/login', to: redirect('/login')

  # 実験応募ページ
  resources :applications

  # カレンダー確認ページ
  get   '/calendar', to: 'calendar#index'

  # アカウント登録用ページ(for 実験者)
  get  '/member/register', to: 'members#new'
  post '/member/register', to: 'members#create'

  # アカウント有効化ページ(for 被験者)
  get '/activate', to: 'participant_activations#edit'

  # メール更新ページ(for 被験者)
  get '/email_update', to: 'participants_email_update#update'

  # 問い合わせフォーム(for 被験者)
  get  '/inquiries',     to: 'inquiries#index'
  post '/inquiries/new', to: 'inquiries#create'
  get  '/inquiries/new', to: 'inquiries#new'
  #get  '/inquire/:id', to: 'inquiries#show', as: 'inquiry'

  # パスワードリセットフォーム(for 被験者)
  get    '/reset',     to: 'participant_password_resets#new'
  post   '/reset',     to: 'participant_password_resets#create'
  get    '/reset/:id', to: 'participant_password_resets#edit',   as: 'edit_reset'
  patch  '/reset/:id', to: 'participant_password_resets#update', as: 'update_reset'

  # 実験者マイページ
  get   '/member/mypage',      to: 'members#show'
  #get   '/member/mypage/edit', to: 'members#edit'
  #patch '/member/mypage/edit', to: 'members#update'
  #put   '/member/mypage/edit', to: 'members#update'

  # 認証ページ(for 実験者)
  get    '/member/login',  to: 'sessions#new_member'
  post   '/member/login',  to: 'sessions#create_member'
  delete '/member/logout', to: 'sessions#destroy_member'

  # 実験募集ページ
  resources :experiments do
    collection do
      get 'place_checkbox'
    end
  end

  #実験部屋追加ページ
  resources :rooms

  #実験場所追加ページ
  resources :places

  # アカウント有効化ページ(for 実験者)
  get '/member/activate', to: 'member_activations#edit'

  # パスワードリセットフォーム(for 実験者)
  get    '/member/reset',     to: 'member_password_resets#new'
  post   '/member/reset',     to: 'member_password_resets#create'
  get    '/member/reset/:id', to: 'member_password_resets#edit',   as: 'member_edit_reset'
  patch  '/member/reset/:id', to: 'member_password_resets#update', as: 'member_update_reset'

  # admin付与ページ
  get    '/member/approve',     to: 'approve_members#show'
  patch  '/member/approve/:id', to: 'approve_members#update', as: 'update_member_admin'
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :places

  validates :name, presence: true, length: { maximum: 50 }, uniqueness: true
  validate :validate_unique_record

  def validate_unique_record
    n = name.tr('０-９ａ-ｚa-zＡ-Ｚ　ァ-ン', '0-9A-ZA-ZA-Z ぁ-ん')
    rn = Room.all.map{ |a| a.name.tr('０-９ａ-ｚa-zＡ-Ｚ　ァ-ン', '0-9A-ZA-ZA-Z ぁ-ん') }
    r = rn.include?(n)
    if r
      errors.add(:base, '既に登録されている部屋です。')
    end
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  include MembersCommon
  before_action :redirect_to_member_login
  before_action :redirect_to_member_mypage_exclude_admin

  def index
    redirect_to member_mypage_url
  end

  def new
    @room = Room.new
    @place = Place.new
  end

  def create
    @type = params[:type]
    if @type == 'room'
      @room = Room.new(params.require(:room).permit(:name))
      if @room.save
        flash[:info] = "部屋を追加しました。"
        redirect_to new_room_url
      else
        @place = Place.new
        render 'new'
      end
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def show
  end
end

app/views/rooms/_form.html.erb
<%= form_for(room, url: form_for_url, html: { class: "form-horizontal" }) do |f| %>
  <%= render 'shared/error_messages', object: f.object if show_errors %>

  <%= hidden_field_tag :type, type %>
  <% if type == 'room' %>
    <div class='form-group'>
      <%= label('dummy',"既存の部屋", class: 'col-sm-2 control-label') %>
      <div class='col-sm-8'>
        <% Room.all.each do |r| %>
        <%= r.name %>
        <% end %>
      </div>
    </div>
    <%= form_text_field f, :name, '部屋名' %>
  <% end %>
  <% if type == 'place' %>
  <div class='form-group'>
    <%= label('dummy',"既存の場所", class: 'col-sm-2 control-label') %>
    <div class='col-sm-8'>
      <% Room.all.each do |r| %>
       <b>
        <%= r.name %>
       </b>
        <% Place.where(room_id: r.id).each do |p| %>
          <%= p.detail %>
        <% end %>
        <br>
      <% end %>
    </div>
  </div>
    <%= form_collection_select f, :room_id, '実施場所', Room.all, :id, :name, prompt: "-------------------------------------------------------" %>
    <%= form_text_field f, :detail, '場所名' %>
  <% end %>
  <%= form_submit f, submit_label %>
<% end %>

app/views/rooms/new.html.erb
<% provide(:title, '実験場所追加フォーム') %>
<h2><%= yield(:title) %></h2>
<div class="panel panel-primary">
  <div class="panel-heading"><%= simple_format("部屋追加") %></div>
  <div class="panel-body">
    <%= render partial: 'form',
               locals: { form_for_url: rooms_path, room: @room, submit_label: '追加する', type: 'room', show_errors: true } %>
  </div>
</div>

<div class="panel panel-primary">
  <div class="panel-heading"><%= simple_format("場所追加") %></div>
  <div class="panel-body">
    <%= render partial: 'form',
               locals: { form_for_url: places_path, room: @place, submit_label: '追加する', type: 'place', show_errors: true } %>
  </div>
</div>